ir node
neo-ngd/neo-plugins pull request #3
Opened 2020-10-15 07:55 UTC by doubiliu

2020-11-04 07:31 UTC, joeqian10 commented on src/FSStorage/FSStorage.cs
> +
override `name`

2020-11-04 09:42 UTC, joeqian10 commented on src/FSStorage/innerring/invoke/ContractInvoker.Fs.cs
> +            client.InvokeLocalFunction(FsContractHash, CheckIsInnerRingMethod, p.Id, p.UserAccount, p.Amount, p.LockAccount);
`method` param should be `ChequeMethod`?

2020-11-04 09:45 UTC, joeqian10 commented on src/FSStorage/innerring/invoke/ContractInvoker.NetMap.cs
> +            client.InvokeFunction(NetMapContractHash, SetConfigMethod, ExtraFee, epoch);
`method` param should be `SetNewEpochMethod`?

2020-11-06 06:30 UTC, joeqian10 commented on src/FSStorage/morph/event/Listener.cs
> +            if (parsers.TryGetValue(p.ScriptHashWithType, out _))
I think this `if` clause is not needed.

2020-11-06 07:12 UTC, joeqian10 commented on src/FSStorage/morph/event/MorphEvent.ContainerContractEvent.cs
> +            containerPutEvent.PublicKey = eventParams[1].GetSpan().ToArray().AsSerializable<ECPoint>(1);
`eventParams[1]` again?

2020-11-06 07:12 UTC, joeqian10 commented on src/FSStorage/morph/event/MorphEvent.ContainerContractEvent.cs
> +            if (eventParams.Count != 2) throw new Exception();
3?

2020-11-06 07:14 UTC, joeqian10 commented on src/FSStorage/morph/event/MorphEvent.FSContractEvent.cs
> +        public class UnBindEvent : IContractEvent
Rename to `UnbindEvent`.

2020-11-06 07:15 UTC, joeqian10 commented on src/FSStorage/morph/event/MorphEvent.FSContractEvent.cs
> +            var bindKeys = ((VM.Types.Array)eventParams[0]).GetEnumerator();
Should be `eventParams[1]` ?

2020-11-06 07:15 UTC, joeqian10 commented on src/FSStorage/morph/event/MorphEvent.FSContractEvent.cs
> +            var bindKeys = ((VM.Types.Array)eventParams[0]).GetEnumerator();
Same as above

2020-11-06 07:19 UTC, joeqian10 commented on src/FSStorage/morph/event/MorphEvent.NetMapContractEvent.cs
> +            updatePeerEvent.Status = (uint)eventParams[0].GetInteger();
should be `eventParams[1]`

2020-11-06 07:41 UTC, joeqian10 commented on src/FSStorage/util/WorkerPool.cs
> +            taskArray.Add(newTask.task);
`hasUsed++`

2020-11-06 07:58 UTC, joeqian10 requested changes
Good job! @doubiliu

2020-11-23 09:42 UTC, ZhangTao1596 requested changes

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/FSStorage/config.json
> +    "workers.alphabet": "10",
```suggestion
    "Workers": {
        "Netmap": "10",
        "Neofs": "10",
        "Balance": "10",
        "Container": "10",
        "Alphabet": "10",
    }
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/IActiveState.cs
> +        public bool IsActive();
```suggestion
       bool IsActive();
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/IEpochState.cs
> +        public ulong EpochCounter();
```suggestion
       void SetEpochCounter(ulong epoch);
       ulong EpochCounter();
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/IEpochTimerReseter.cs
> +        public void ResetEpochTimer();
```suggestion
       void ResetEpochTimer();
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/IIndexer.cs
> +        public void SetIndexer(int index);
```suggestion
       int Index();
       void SetIndexer(int index);
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/IProcessor.cs
> +        public HandlerInfo[] TimersHandlers();
```suggestion
       ParserInfo[] ListenerParsers();
       HandlerInfo[] ListenerHandlers();
       HandlerInfo[] TimersHandlers();
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/FSStorage/config.json
> +    "contracts.alphabet0": "0x496d839a9ccdd364066323dd7bde210dfa7267e2",
```suggestion
    "Contracts": {
        "Netmap": "0x3fafa517cd771afcbd744e9194065657804ef683",
        "Neofs": "0xbbf24e35a65a9102443206921e0a2479af7b8f9c",
        "NeofsId": "0xd376487192d0ff8f03b5878be657337e8308709b",
        "Balance": "0x79246b19e980225044b8dcef52328ec637d6b887",
        "Container": "0x4a445a72c5dba72c0c4e4634cff86c48dfe2c396",
        "Alphabet": "1",
        "Alphabet0": "0x496d839a9ccdd364066323dd7bde210dfa7267e2",
    }
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/FSStorage/config.json
> +    "timers.emit": 100,
```suggestion
    "Timers": {
        "Epoch": 100,
        "Emit": 100,
    }
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/FSStorage/config.json
> +    "netmap_cleaner.threshold": 2,
```suggestion
    "NetmapCleaner": {
        "Enabled": true,
        "Threshold": 2,
    }
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/FSStorage/config.json
> +    "emit.storage.amount": 2,
```suggestion
    "Emit": {
        "Mint": {
            "CacheSize": 100,
            "Threshold": 100,
            "Value": 2,
        },
        "Storage": {
            "Amount": 2,
        }
    }
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +            long epoch = 0;
```suggestion
            long epoch;
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +            catch (Exception e)
```suggestion
            catch (Exception)
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +            int index = 0;
```suggestion
            int index;
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +            catch (Exception e)
```suggestion
            catch (Exception)
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +            uint balancePrecision = 0;
```suggestion
            uint balancePrecision;
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +            catch (Exception e)
```suggestion
            catch (Exception)
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +                case Start start:
```suggestion
                case Start _:
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +                case Stop stop:
```suggestion
                case Stop _:
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +        }
Use ` Interlocked.Exchange(ref long, long)` ? Why use db？

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +        }
Use `Interlocked.Exchange(ref long, long)`?

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/invoke/ContractInvoker.Balance.cs
> +            public byte[] Comment { get => comment; set => comment = value; }
Why not just use like `public byte[] Sender;`?

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/InnerRingService.cs
> +    public class InnerRingService : UntypedActor, IActiveState, IEpochState, IEpochTimerReseter, IIndexer
Use `InnerRingService` directly and remove `IActiveState, IEpochState, IEpochTimerReseter, IIndexer`?
Only `InnerRingService` implement these interfaces.

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/invoke/ContractInvoker.NetMap.cs
> +                NeoFS.API.v2.Netmap.NodeInfo node = NeoFS.API.v2.Netmap.NodeInfo.Parser.ParseFrom(rawNodeInfo);
```suggestion
                NodeInfo node = NodeInfo.Parser.ParseFrom(rawNodeInfo);
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/invoke/ContractInvoker.Balance.cs
> +            return (uint)(result.ResultStack[0].GetInteger());
```suggestion
            return (uint)result.ResultStack[0].GetInteger();
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/invoke/ContractInvoker.Fs.cs
> +        private static UInt160 FsContractHash = Settings.Default.FsContractHash;
```suggestion
        private static UInt160 FsContractHash => Settings.Default.FsContractHash;
```
like this?

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/AlphabetContractProcessor.cs
> +        public Client Client { get => client; set => client = value; }
Why not just use `public Client Client;` directly?

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/AlphabetContractProcessor.cs
> +        private UInt160[] AlphabetContractHash => Settings.Default.AlphabetContractHash;
Unused.

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/AlphabetContractProcessor.cs
> +        public void ProcessEmit(NewAlphabetEmitTickEvent newAlphabetEmitTickEvent)
Argument unused.

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/AlphabetContractProcessor.cs
> +            Utility.Log("tick", LogLevel.Info, pairs.ToString());
`Dictionary.ToString()` will print ```System.Collections.Generic.Dictionary`2[System.String,System.String]```.
This will not print you expect.

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/AlphabetContractProcessor.cs
> +                Utility.Log("can't get netmap snapshot to emit gas to storage nodes", LogLevel.Warning, pairs.ToString());
This will not print you expect.

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/AlphabetContractProcessor.cs
> +            catch (Exception e)
```suggestion
            catch (Exception)
```

2020-11-23 09:42 UTC, ZhangTao1596 commented on src/FSStorage/innerring/processors/BalanceContractProcessor.cs
> +            Utility.Log("notification", LogLevel.Info, pairs.ToString());
This will not print you expect.

2020-11-23 09:45 UTC, ZhangTao1596 commented
Use camel case directory name.

2021-01-19 07:21 UTC, closed without merging